FROM registry.access.redhat.com/ubi9/go-toolset as builder
COPY go.mod go.mod
COPY go.sum go.sum
COPY *.go ./
COPY ./cmd/metro2 ./cmd/metro2
COPY ./pkg ./pkg
COPY ./test ./test
COPY makefile makefile
RUN make build

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5-1738643652
ARG VERSION=unknown
LABEL maintainer="Moov <oss@moov.io>"
LABEL name="metro2"
LABEL version=$VERSION

COPY --from=builder /opt/app-root/src/bin/metro2 /bin/metro2

ENTRYPOINT ["/bin/metro2"]
CMD ["web"]
