# Step one: build scapresults
FROM registry.access.redhat.com/ubi8/go-toolset as builder
COPY . .
RUN make build

FROM registry.access.redhat.com/ubi8/ubi-minimal

ARG VERSION=unknown
LABEL maintainer="Moov <oss@moov.io>"
LABEL name="metro2"
LABEL version=$VERSION

COPY --from=builder /opt/app-root/src/bin/metro2 /bin/metro2

ENTRYPOINT ["/bin/metro2"]
CMD ["web"]
