source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "bulma-clean-theme"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]

# Patched transitive gems for Dependabot alerts on Gemfile.lock.
# Stay on the github-pages 7.2 Active Support line instead of 8.x.
gem "activesupport", ">= 7.2.3.1", "< 9"
gem "addressable", ">= 2.9.0"
gem "concurrent-ruby", ">= 1.3.7"
gem "faraday", ">= 2.14.3"
gem "nokogiri", ">= 1.19.4"
gem "rexml", ">= 3.4.2"
gem "uri", ">= 0.13.3"

