/*
 * METRO2 API
 *
 * Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// DataRecord struct for DataRecord
type DataRecord struct {
	Base BaseSegment `json:"base"`
	J1   []J1Segment `json:"j1,omitempty"`
	J2   []J2Segment `json:"j2,omitempty"`
	K1   K1Segment   `json:"k1,omitempty"`
	K2   K2Segment   `json:"k2,omitempty"`
	K3   K3Segment   `json:"k3,omitempty"`
	K4   K4Segment   `json:"k4,omitempty"`
	L1   L1Segment   `json:"l1,omitempty"`
	N1   N1Segment   `json:"n1,omitempty"`
}
