/*
 * METRO2 API
 *
 * Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// BaseSegment struct for BaseSegment
type BaseSegment struct {
	BlockDescriptorWord           int32     `json:"blockDescriptorWord,omitempty"`
	RecordDescriptorWord          int32     `json:"recordDescriptorWord"`
	TimeStamp                     time.Time `json:"timeStamp,omitempty"`
	IdentificationNumber          string    `json:"identificationNumber"`
	CycleIdentifier               string    `json:"cycleIdentifier,omitempty"`
	ConsumerAccountNumber         string    `json:"consumerAccountNumber"`
	PortfolioType                 string    `json:"portfolioType,omitempty"`
	AccountType                   string    `json:"accountType"`
	DateOpened                    time.Time `json:"dateOpened,omitempty"`
	CreditLimit                   int32     `json:"creditLimit,omitempty"`
	HighestCredit                 int32     `json:"highestCredit"`
	TermsDuration                 string    `json:"termsDuration"`
	TermsFrequency                string    `json:"termsFrequency,omitempty"`
	ScheduledMonthlyPaymentAmount int32     `json:"scheduledMonthlyPaymentAmount,omitempty"`
	ActualPaymentAmount           int32     `json:"actualPaymentAmount,omitempty"`
	AccountStatus                 string    `json:"accountStatus"`
	PaymentRating                 string    `json:"paymentRating,omitempty"`
	PaymentHistoryProfile         string    `json:"paymentHistoryProfile"`
	SpecialComment                string    `json:"specialComment,omitempty"`
	ComplianceConditionCode       string    `json:"complianceConditionCode,omitempty"`
	CurrentBalance                int32     `json:"currentBalance"`
	AmountPastDue                 int32     `json:"amountPastDue,omitempty"`
	OriginalChargeOffAmount       int32     `json:"originalChargeOffAmount,omitempty"`
	DateAccountInformation        time.Time `json:"dateAccountInformation"`
	DateFirstDelinquency          time.Time `json:"dateFirstDelinquency,omitempty"`
	DateClosed                    time.Time `json:"dateClosed,omitempty"`
	DateLastPayment               time.Time `json:"dateLastPayment,omitempty"`
	InterestTypeIndicator         string    `json:"interestTypeIndicator,omitempty"`
	Surname                       string    `json:"surname"`
	FirstName                     string    `json:"firstName"`
	MiddleName                    string    `json:"middleName,omitempty"`
	GenerationCode                string    `json:"generationCode,omitempty"`
	SocialSecurityNumber          int32     `json:"socialSecurityNumber"`
	DateBirth                     time.Time `json:"dateBirth"`
	TelephoneNumber               int64     `json:"telephoneNumber,omitempty"`
	EcoaCode                      string    `json:"ecoaCode"`
	ConsumerInformationIndicator  string    `json:"consumerInformationIndicator,omitempty"`
	CountryCode                   string    `json:"countryCode,omitempty"`
	FirstLineAddress              string    `json:"firstLineAddress"`
	SecondLineAddress             string    `json:"secondLineAddress,omitempty"`
	City                          string    `json:"city,omitempty"`
	State                         string    `json:"state"`
	ZipCode                       string    `json:"zipCode"`
	AddressIndicator              string    `json:"addressIndicator,omitempty"`
	ResidenceCode                 string    `json:"residenceCode,omitempty"`
}
