/*
METRO2 API

Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
	"time"
)

// checks if the J2Segment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &J2Segment{}

// J2Segment struct for J2Segment
type J2Segment struct {
	SegmentIdentifier            string     `json:"segmentIdentifier"`
	Surname                      string     `json:"surname"`
	FirstName                    string     `json:"firstName"`
	MiddleName                   *string    `json:"middleName,omitempty"`
	GenerationCode               *string    `json:"generationCode,omitempty"`
	SocialSecurityNumber         *int32     `json:"socialSecurityNumber,omitempty"`
	DateBirth                    *time.Time `json:"dateBirth,omitempty"`
	TelephoneNumber              *int64     `json:"telephoneNumber,omitempty"`
	EcoaCode                     string     `json:"ecoaCode"`
	ConsumerInformationIndicator *string    `json:"consumerInformationIndicator,omitempty"`
	CountryCode                  *string    `json:"countryCode,omitempty"`
	FirstLineAddress             string     `json:"firstLineAddress"`
	SecondLineAddress            *string    `json:"secondLineAddress,omitempty"`
	City                         string     `json:"city"`
	State                        string     `json:"state"`
	ZipCode                      string     `json:"zipCode"`
	AddressIndicator             *string    `json:"addressIndicator,omitempty"`
	ResidenceCode                *string    `json:"residenceCode,omitempty"`
}

// NewJ2Segment instantiates a new J2Segment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJ2Segment(segmentIdentifier string, surname string, firstName string, ecoaCode string, firstLineAddress string, city string, state string, zipCode string) *J2Segment {
	this := J2Segment{}
	this.SegmentIdentifier = segmentIdentifier
	this.Surname = surname
	this.FirstName = firstName
	this.EcoaCode = ecoaCode
	this.FirstLineAddress = firstLineAddress
	this.City = city
	this.State = state
	this.ZipCode = zipCode
	return &this
}

// NewJ2SegmentWithDefaults instantiates a new J2Segment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJ2SegmentWithDefaults() *J2Segment {
	this := J2Segment{}
	return &this
}

// GetSegmentIdentifier returns the SegmentIdentifier field value
func (o *J2Segment) GetSegmentIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SegmentIdentifier
}

// GetSegmentIdentifierOk returns a tuple with the SegmentIdentifier field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetSegmentIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SegmentIdentifier, true
}

// SetSegmentIdentifier sets field value
func (o *J2Segment) SetSegmentIdentifier(v string) {
	o.SegmentIdentifier = v
}

// GetSurname returns the Surname field value
func (o *J2Segment) GetSurname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Surname
}

// GetSurnameOk returns a tuple with the Surname field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetSurnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Surname, true
}

// SetSurname sets field value
func (o *J2Segment) SetSurname(v string) {
	o.Surname = v
}

// GetFirstName returns the FirstName field value
func (o *J2Segment) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *J2Segment) SetFirstName(v string) {
	o.FirstName = v
}

// GetMiddleName returns the MiddleName field value if set, zero value otherwise.
func (o *J2Segment) GetMiddleName() string {
	if o == nil || IsNil(o.MiddleName) {
		var ret string
		return ret
	}
	return *o.MiddleName
}

// GetMiddleNameOk returns a tuple with the MiddleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetMiddleNameOk() (*string, bool) {
	if o == nil || IsNil(o.MiddleName) {
		return nil, false
	}
	return o.MiddleName, true
}

// HasMiddleName returns a boolean if a field has been set.
func (o *J2Segment) HasMiddleName() bool {
	if o != nil && !IsNil(o.MiddleName) {
		return true
	}

	return false
}

// SetMiddleName gets a reference to the given string and assigns it to the MiddleName field.
func (o *J2Segment) SetMiddleName(v string) {
	o.MiddleName = &v
}

// GetGenerationCode returns the GenerationCode field value if set, zero value otherwise.
func (o *J2Segment) GetGenerationCode() string {
	if o == nil || IsNil(o.GenerationCode) {
		var ret string
		return ret
	}
	return *o.GenerationCode
}

// GetGenerationCodeOk returns a tuple with the GenerationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetGenerationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.GenerationCode) {
		return nil, false
	}
	return o.GenerationCode, true
}

// HasGenerationCode returns a boolean if a field has been set.
func (o *J2Segment) HasGenerationCode() bool {
	if o != nil && !IsNil(o.GenerationCode) {
		return true
	}

	return false
}

// SetGenerationCode gets a reference to the given string and assigns it to the GenerationCode field.
func (o *J2Segment) SetGenerationCode(v string) {
	o.GenerationCode = &v
}

// GetSocialSecurityNumber returns the SocialSecurityNumber field value if set, zero value otherwise.
func (o *J2Segment) GetSocialSecurityNumber() int32 {
	if o == nil || IsNil(o.SocialSecurityNumber) {
		var ret int32
		return ret
	}
	return *o.SocialSecurityNumber
}

// GetSocialSecurityNumberOk returns a tuple with the SocialSecurityNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetSocialSecurityNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.SocialSecurityNumber) {
		return nil, false
	}
	return o.SocialSecurityNumber, true
}

// HasSocialSecurityNumber returns a boolean if a field has been set.
func (o *J2Segment) HasSocialSecurityNumber() bool {
	if o != nil && !IsNil(o.SocialSecurityNumber) {
		return true
	}

	return false
}

// SetSocialSecurityNumber gets a reference to the given int32 and assigns it to the SocialSecurityNumber field.
func (o *J2Segment) SetSocialSecurityNumber(v int32) {
	o.SocialSecurityNumber = &v
}

// GetDateBirth returns the DateBirth field value if set, zero value otherwise.
func (o *J2Segment) GetDateBirth() time.Time {
	if o == nil || IsNil(o.DateBirth) {
		var ret time.Time
		return ret
	}
	return *o.DateBirth
}

// GetDateBirthOk returns a tuple with the DateBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetDateBirthOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateBirth) {
		return nil, false
	}
	return o.DateBirth, true
}

// HasDateBirth returns a boolean if a field has been set.
func (o *J2Segment) HasDateBirth() bool {
	if o != nil && !IsNil(o.DateBirth) {
		return true
	}

	return false
}

// SetDateBirth gets a reference to the given time.Time and assigns it to the DateBirth field.
func (o *J2Segment) SetDateBirth(v time.Time) {
	o.DateBirth = &v
}

// GetTelephoneNumber returns the TelephoneNumber field value if set, zero value otherwise.
func (o *J2Segment) GetTelephoneNumber() int64 {
	if o == nil || IsNil(o.TelephoneNumber) {
		var ret int64
		return ret
	}
	return *o.TelephoneNumber
}

// GetTelephoneNumberOk returns a tuple with the TelephoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetTelephoneNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.TelephoneNumber) {
		return nil, false
	}
	return o.TelephoneNumber, true
}

// HasTelephoneNumber returns a boolean if a field has been set.
func (o *J2Segment) HasTelephoneNumber() bool {
	if o != nil && !IsNil(o.TelephoneNumber) {
		return true
	}

	return false
}

// SetTelephoneNumber gets a reference to the given int64 and assigns it to the TelephoneNumber field.
func (o *J2Segment) SetTelephoneNumber(v int64) {
	o.TelephoneNumber = &v
}

// GetEcoaCode returns the EcoaCode field value
func (o *J2Segment) GetEcoaCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EcoaCode
}

// GetEcoaCodeOk returns a tuple with the EcoaCode field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetEcoaCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EcoaCode, true
}

// SetEcoaCode sets field value
func (o *J2Segment) SetEcoaCode(v string) {
	o.EcoaCode = v
}

// GetConsumerInformationIndicator returns the ConsumerInformationIndicator field value if set, zero value otherwise.
func (o *J2Segment) GetConsumerInformationIndicator() string {
	if o == nil || IsNil(o.ConsumerInformationIndicator) {
		var ret string
		return ret
	}
	return *o.ConsumerInformationIndicator
}

// GetConsumerInformationIndicatorOk returns a tuple with the ConsumerInformationIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetConsumerInformationIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.ConsumerInformationIndicator) {
		return nil, false
	}
	return o.ConsumerInformationIndicator, true
}

// HasConsumerInformationIndicator returns a boolean if a field has been set.
func (o *J2Segment) HasConsumerInformationIndicator() bool {
	if o != nil && !IsNil(o.ConsumerInformationIndicator) {
		return true
	}

	return false
}

// SetConsumerInformationIndicator gets a reference to the given string and assigns it to the ConsumerInformationIndicator field.
func (o *J2Segment) SetConsumerInformationIndicator(v string) {
	o.ConsumerInformationIndicator = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *J2Segment) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *J2Segment) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *J2Segment) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetFirstLineAddress returns the FirstLineAddress field value
func (o *J2Segment) GetFirstLineAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstLineAddress
}

// GetFirstLineAddressOk returns a tuple with the FirstLineAddress field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetFirstLineAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstLineAddress, true
}

// SetFirstLineAddress sets field value
func (o *J2Segment) SetFirstLineAddress(v string) {
	o.FirstLineAddress = v
}

// GetSecondLineAddress returns the SecondLineAddress field value if set, zero value otherwise.
func (o *J2Segment) GetSecondLineAddress() string {
	if o == nil || IsNil(o.SecondLineAddress) {
		var ret string
		return ret
	}
	return *o.SecondLineAddress
}

// GetSecondLineAddressOk returns a tuple with the SecondLineAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetSecondLineAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SecondLineAddress) {
		return nil, false
	}
	return o.SecondLineAddress, true
}

// HasSecondLineAddress returns a boolean if a field has been set.
func (o *J2Segment) HasSecondLineAddress() bool {
	if o != nil && !IsNil(o.SecondLineAddress) {
		return true
	}

	return false
}

// SetSecondLineAddress gets a reference to the given string and assigns it to the SecondLineAddress field.
func (o *J2Segment) SetSecondLineAddress(v string) {
	o.SecondLineAddress = &v
}

// GetCity returns the City field value
func (o *J2Segment) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *J2Segment) SetCity(v string) {
	o.City = v
}

// GetState returns the State field value
func (o *J2Segment) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *J2Segment) SetState(v string) {
	o.State = v
}

// GetZipCode returns the ZipCode field value
func (o *J2Segment) GetZipCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ZipCode
}

// GetZipCodeOk returns a tuple with the ZipCode field value
// and a boolean to check if the value has been set.
func (o *J2Segment) GetZipCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZipCode, true
}

// SetZipCode sets field value
func (o *J2Segment) SetZipCode(v string) {
	o.ZipCode = v
}

// GetAddressIndicator returns the AddressIndicator field value if set, zero value otherwise.
func (o *J2Segment) GetAddressIndicator() string {
	if o == nil || IsNil(o.AddressIndicator) {
		var ret string
		return ret
	}
	return *o.AddressIndicator
}

// GetAddressIndicatorOk returns a tuple with the AddressIndicator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetAddressIndicatorOk() (*string, bool) {
	if o == nil || IsNil(o.AddressIndicator) {
		return nil, false
	}
	return o.AddressIndicator, true
}

// HasAddressIndicator returns a boolean if a field has been set.
func (o *J2Segment) HasAddressIndicator() bool {
	if o != nil && !IsNil(o.AddressIndicator) {
		return true
	}

	return false
}

// SetAddressIndicator gets a reference to the given string and assigns it to the AddressIndicator field.
func (o *J2Segment) SetAddressIndicator(v string) {
	o.AddressIndicator = &v
}

// GetResidenceCode returns the ResidenceCode field value if set, zero value otherwise.
func (o *J2Segment) GetResidenceCode() string {
	if o == nil || IsNil(o.ResidenceCode) {
		var ret string
		return ret
	}
	return *o.ResidenceCode
}

// GetResidenceCodeOk returns a tuple with the ResidenceCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *J2Segment) GetResidenceCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ResidenceCode) {
		return nil, false
	}
	return o.ResidenceCode, true
}

// HasResidenceCode returns a boolean if a field has been set.
func (o *J2Segment) HasResidenceCode() bool {
	if o != nil && !IsNil(o.ResidenceCode) {
		return true
	}

	return false
}

// SetResidenceCode gets a reference to the given string and assigns it to the ResidenceCode field.
func (o *J2Segment) SetResidenceCode(v string) {
	o.ResidenceCode = &v
}

func (o J2Segment) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o J2Segment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["segmentIdentifier"] = o.SegmentIdentifier
	toSerialize["surname"] = o.Surname
	toSerialize["firstName"] = o.FirstName
	if !IsNil(o.MiddleName) {
		toSerialize["middleName"] = o.MiddleName
	}
	if !IsNil(o.GenerationCode) {
		toSerialize["generationCode"] = o.GenerationCode
	}
	if !IsNil(o.SocialSecurityNumber) {
		toSerialize["socialSecurityNumber"] = o.SocialSecurityNumber
	}
	if !IsNil(o.DateBirth) {
		toSerialize["dateBirth"] = o.DateBirth
	}
	if !IsNil(o.TelephoneNumber) {
		toSerialize["telephoneNumber"] = o.TelephoneNumber
	}
	toSerialize["ecoaCode"] = o.EcoaCode
	if !IsNil(o.ConsumerInformationIndicator) {
		toSerialize["consumerInformationIndicator"] = o.ConsumerInformationIndicator
	}
	if !IsNil(o.CountryCode) {
		toSerialize["countryCode"] = o.CountryCode
	}
	toSerialize["firstLineAddress"] = o.FirstLineAddress
	if !IsNil(o.SecondLineAddress) {
		toSerialize["secondLineAddress"] = o.SecondLineAddress
	}
	toSerialize["city"] = o.City
	toSerialize["state"] = o.State
	toSerialize["zipCode"] = o.ZipCode
	if !IsNil(o.AddressIndicator) {
		toSerialize["addressIndicator"] = o.AddressIndicator
	}
	if !IsNil(o.ResidenceCode) {
		toSerialize["residenceCode"] = o.ResidenceCode
	}
	return toSerialize, nil
}

type NullableJ2Segment struct {
	value *J2Segment
	isSet bool
}

func (v NullableJ2Segment) Get() *J2Segment {
	return v.value
}

func (v *NullableJ2Segment) Set(val *J2Segment) {
	v.value = val
	v.isSet = true
}

func (v NullableJ2Segment) IsSet() bool {
	return v.isSet
}

func (v *NullableJ2Segment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJ2Segment(val *J2Segment) *NullableJ2Segment {
	return &NullableJ2Segment{value: val, isSet: true}
}

func (v NullableJ2Segment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJ2Segment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
