/*
 * METRO2 API
 *
 * Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// N1Segment struct for N1Segment
type N1Segment struct {
	SegmentIdentifier         string `json:"segmentIdentifier"`
	EmployerName              string `json:"employerName"`
	FirstLineEmployerAddress  string `json:"firstLineEmployerAddress,omitempty"`
	SecondLineEmployerAddress string `json:"secondLineEmployerAddress,omitempty"`
	EmployerCity              string `json:"employerCity,omitempty"`
	EmployerState             string `json:"employerState,omitempty"`
	ZipCode                   string `json:"zipCode,omitempty"`
	Occupation                string `json:"occupation,omitempty"`
}
