/*
 * METRO2 API
 *
 * Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// K4Segment struct for K4Segment
type K4Segment struct {
	SegmentIdentifier           string    `json:"segmentIdentifier"`
	SpecializedPaymentIndicator int32     `json:"specializedPaymentIndicator"`
	DeferredPaymentStartDate    time.Time `json:"deferredPaymentStartDate,omitempty"`
	BalloonPaymentDueDate       time.Time `json:"balloonPaymentDueDate,omitempty"`
	BalloonPaymentAmount        int32     `json:"balloonPaymentAmount,omitempty"`
}
