/*
 * METRO2 API
 *
 * Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// TrailerRecord struct for TrailerRecord
type TrailerRecord struct {
	BlockDescriptorWord              int32  `json:"blockDescriptorWord,omitempty"`
	RecordDescriptorWord             int32  `json:"recordDescriptorWord"`
	RecordIdentifier                 string `json:"recordIdentifier"`
	TotalBaseRecords                 int32  `json:"totalBaseRecords,omitempty"`
	TotalStatusCodeDF                int32  `json:"totalStatusCodeDF,omitempty"`
	TotalConsumerSegmentsJ1          int32  `json:"totalConsumerSegmentsJ1,omitempty"`
	TotalConsumerSegmentsJ2          int32  `json:"totalConsumerSegmentsJ2,omitempty"`
	BlockCount                       int32  `json:"blockCount,omitempty"`
	TotalStatusCodeDA                int32  `json:"totalStatusCodeDA,omitempty"`
	TotalStatusCode05                int32  `json:"totalStatusCode05,omitempty"`
	TotalStatusCode11                int32  `json:"totalStatusCode11,omitempty"`
	TotalStatusCode13                int32  `json:"totalStatusCode13,omitempty"`
	TotalStatusCode61                int32  `json:"totalStatusCode61,omitempty"`
	TotalStatusCode62                int32  `json:"totalStatusCode62,omitempty"`
	TotalStatusCode63                int32  `json:"totalStatusCode63,omitempty"`
	TotalStatusCode64                int32  `json:"totalStatusCode64,omitempty"`
	TotalStatusCode65                int32  `json:"totalStatusCode65,omitempty"`
	TotalStatusCode71                int32  `json:"totalStatusCode71,omitempty"`
	TotalStatusCode78                int32  `json:"totalStatusCode78,omitempty"`
	TotalStatusCode80                int32  `json:"totalStatusCode80,omitempty"`
	TotalStatusCode82                int32  `json:"totalStatusCode82,omitempty"`
	TotalStatusCode83                int32  `json:"totalStatusCode83,omitempty"`
	TotalStatusCode84                int32  `json:"totalStatusCode84,omitempty"`
	TotalStatusCode88                int32  `json:"totalStatusCode88,omitempty"`
	TotalStatusCode89                int32  `json:"totalStatusCode89,omitempty"`
	TotalStatusCode93                int32  `json:"totalStatusCode93,omitempty"`
	TotalStatusCode94                int32  `json:"totalStatusCode94,omitempty"`
	TotalStatusCode95                int32  `json:"totalStatusCode95,omitempty"`
	TotalStatusCode96                int32  `json:"totalStatusCode96,omitempty"`
	TotalStatusCode97                int32  `json:"totalStatusCode97,omitempty"`
	TotalECOACodeZ                   int32  `json:"totalECOACodeZ,omitempty"`
	TotalEmploymentSegments          int32  `json:"totalEmploymentSegments,omitempty"`
	TotalOriginalCreditorSegments    int32  `json:"totalOriginalCreditorSegments,omitempty"`
	TotalPurchasedToSegments         int32  `json:"totalPurchasedToSegments,omitempty"`
	TotalMortgageInformationSegments int32  `json:"totalMortgageInformationSegments,omitempty"`
	TotalPaymentInformationSegments  int32  `json:"totalPaymentInformationSegments,omitempty"`
	TotalChangeSegments              int32  `json:"totalChangeSegments,omitempty"`
	TotalSocialNumbersAllSegments    int32  `json:"totalSocialNumbersAllSegments,omitempty"`
	TotalSocialNumbersBaseSegments   int32  `json:"totalSocialNumbersBaseSegments,omitempty"`
	TotalSocialNumbersJ1Segments     int32  `json:"totalSocialNumbersJ1Segments,omitempty"`
	TotalSocialNumbersJ2Segments     int32  `json:"totalSocialNumbersJ2Segments,omitempty"`
	TotalDatesBirthAllSegments       int32  `json:"totalDatesBirthAllSegments,omitempty"`
	TotalDatesBirthBaseSegments      int32  `json:"totalDatesBirthBaseSegments,omitempty"`
	TotalDatesBirthJ1Segments        int32  `json:"totalDatesBirthJ1Segments,omitempty"`
	TotalDatesBirthJ2Segments        int32  `json:"totalDatesBirthJ2Segments,omitempty"`
	TotalTelephoneNumbersAllSegments int32  `json:"totalTelephoneNumbersAllSegments,omitempty"`
}
