/*
 * METRO2 API
 *
 * Moov Metro2 ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating Metro2 files. Metro2 is an open-source consumer credit history report for credit report file creation and validation.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// HeaderRecord struct for HeaderRecord
type HeaderRecord struct {
	BlockDescriptorWord         int32     `json:"blockDescriptorWord,omitempty"`
	RecordDescriptorWord        int32     `json:"recordDescriptorWord"`
	RecordIdentifier            string    `json:"recordIdentifier"`
	CycleIdentifier             string    `json:"cycleIdentifier,omitempty"`
	InnovisProgramIdentifier    string    `json:"innovisProgramIdentifier,omitempty"`
	EquifaxProgramIdentifier    string    `json:"equifaxProgramIdentifier,omitempty"`
	ExperianProgramIdentifier   string    `json:"experianProgramIdentifier,omitempty"`
	TransUnionProgramIdentifier string    `json:"transUnionProgramIdentifier,omitempty"`
	ActivityDate                time.Time `json:"activityDate"`
	DateCreated                 time.Time `json:"dateCreated"`
	ProgramDate                 time.Time `json:"programDate,omitempty"`
	ProgramRevisionDate         time.Time `json:"programRevisionDate,omitempty"`
	ReporterName                string    `json:"reporterName"`
	ReporterAddress             string    `json:"reporterAddress"`
	ReporterTelephoneNumber     int64     `json:"reporterTelephoneNumber,omitempty"`
	SoftwareVendorName          string    `json:"softwareVendorName,omitempty"`
	SoftwareVersionNumber       string    `json:"softwareVersionNumber,omitempty"`
	PrbcProgramIdentifier       string    `json:"prbcProgramIdentifier,omitempty"`
}
