name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Go Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Install make (Windows)
      if: runner.os == 'Windows'
      run: choco install -y make mingw

    - name: Verify OpenAPI
      if: runner.os == 'Linux'
      run: make check-openapi

    - name: Check
      run: make check
      env:
        COVER_THRESHOLD: 85.0
        GOLANGCI_LINTERS: gosec

    - name: Upload Code Coverage
      if: runner.os == 'Linux'
      run: bash <(curl -s https://codecov.io/bash)

  docker:
    name: Docker Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v6
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v5

    - name: Docker Build
      run: make docker
